### ISSUE TITLE
Error running SpectralNet

### ISSUE THREAD

**Issue by gareththegeek** [KlugerLab/SpectralNet#6]
```
>python run.py --dset=mnist
Using TensorFlow backend.
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    from spectralnet import run_net
  File "C:\dev\spectral-clustering\SpectralNet\src\applications\spectralnet.py", line 19, in <module>
    from core import train
  File "C:\dev\spectral-clustering\SpectralNet\src\core\train.py", line 5, in <module>
    from keras.engine.training import _make_batches
ImportError: cannot import name '_make_batches'
```

**Comment by lihenryhfl** [comment]
Hey thanks for pointing this out! The code used a function that no longer exists in the newest version of Keras. I've made the change, just gonna make sure everything still runs correctly, and then I'll push it.

**Comment by lihenryhfl** [comment]
The error should be fixed. Let me know if there are any problems!

**Comment by gareththegeek** [comment]
Looks like it's all sorted in latest, cheers!
